import { nanoid } from "@reduxjs/toolkit";

export const datas = [
  {
    id: nanoid(),
    name: "Airi Satou",
    position: "Accountant",
    office: "Tokyo",
    age: 33,
    date: "11/28/2008",
    salary: "$115,000",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Angelica Ramos",
    position: "Chief Executive Officer (CEO)",
    office: "London",
    age: 47,
    date: "10/9/2009",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Ashton Cox",
    position: "Junior Technical Author",
    office: "San Francisco	",
    age: 66,
    date: "1/12/2009",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Bradley Greer",
    position: "Software Engineer",
    office: "London",
    age: 41,
    date: "10/13/2012",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Brenden Wagner",
    position: "Software Engineer",
    office: "San Francisco	",
    age: 28,
    date: "6/7/2011",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Brielle Williamson",
    position: "Integration Specialist",
    office: "New York	",
    age: 61,
    date: "12/2/2012",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Bruno Nash",
    position: "Software Engineer",
    office: "London",
    age: 38,
    date: "5/3/2011",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Caesar Vance",
    position: "Pre-Sales Support",
    office: "New York",
    age: 21,
    date: "12/12/2011",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Cara Stevens",
    position: "Sales Assistant",
    office: "New York",
    age: 46,
    date: "12/6/2011",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Cedric Kelly",
    position: "Senior Javascript Developer",
    office: "Edinburgh",
    age: 22,
    date: "3/29/2012",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Charde Marshall",
    position: "Regional Director",
    office: "San Francisco",
    age: 36,
    date: "10/16/2008",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Colleen Hurst",
    position: "Javascript Developer",
    office: "San Francisco",
    age: 39,
    date: "9/15/2009",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Dai Rios",
    position: "Personnel Lead",
    office: "Edinburgh",
    age: 35,
    date: "9/26/2012",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Donna Snider",
    position: "Customer Support",
    office: "New York",
    age: 27,
    date: "1/25/2011",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Doris Wilder",
    position: "Sales Assistant",
    office: "Sydney",
    age: 23,
    date: "9/20/2010",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Doris Wilder",
    position: "Sales Assistant",
    office: "Sydney",
    age: 23,
    date: "9/20/2010",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Doris Wilder",
    position: "Sales Assistant",
    office: "Sydney",
    age: 23,
    date: "9/20/2010",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Doris Wilder",
    position: "Sales Assistant",
    office: "Sydney",
    age: 23,
    date: "9/20/2010",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Doris Wilder",
    position: "Sales Assistant",
    office: "Sydney",
    age: 23,
    date: "9/20/2010",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Doris Wilder",
    position: "Sales Assistant",
    office: "Sydney",
    age: 23,
    date: "9/20/2010",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Doris Wilder",
    position: "Sales Assistant",
    office: "Sydney",
    age: 23,
    date: "9/20/2010",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Doris Wilder",
    position: "Sales Assistant",
    office: "Sydney",
    age: 23,
    date: "9/20/2010",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Doris Wilder",
    position: "Sales Assistant",
    office: "Sydney",
    age: 23,
    date: "9/20/2010",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Doris Wilder",
    position: "Sales Assistant",
    office: "Sydney",
    age: 23,
    date: "9/20/2010",
    isShowing: false,
    editData: false,
  },
  {
    id: nanoid(),
    name: "Doris Wilder",
    position: "Sales Assistant",
    office: "Sydney",
    age: 23,
    date: "9/20/2010",
    isShowing: false,
    editData: false,
  },
];
